version: "{build}"

clone_depth: 100

image:
- Visual Studio 2015
- Ubuntu

install:
  - python --version
  # Windows needs python -m prefix to upgrade pip
  - python -m pip install --upgrade pip --disable-pip-version-check
  # Linux needs PATH adjustments
  - sh: export PATH="$PATH:/home/appveyor/.local/bin"
  - pip install scons
  - #python -m pip install lxml
  
build_script:
  - echo --- Build -------------------------------------------------
  - pip show lxml --no-python-version-warning || echo 0
  - scons
