version: "{build}"

clone_depth: 100

image:
- Visual Studio 2015
- Ubuntu

install:
  - python --version
  - pip install --upgrade pip
  - pip install scons
  - #python -m pip install lxml
  
build_script:
  - echo --- Build -------------------------------------------------
  - python -m scons
